# ==========================================================
# REQUEST: C++クライアントが送る目標XYZ座標と角度制約
# ==========================================================
# 目標座標 (m)
float64 x
float64 y
float64 z

#graps
float64 gripper
# ピッチ角の目標値と範囲 (度)
float64 alpha
float64 alpha1
float64 alpha2

---

# ==========================================================
# RESPONSE: Python IKサーバーが返す計算結果
# ==========================================================
# IK計算の成否
bool success
# 計算されたサーボ3, 4, 5, 6のPWMパルス幅 (動作に成功した場合のみ有効)
int32 servo2
int32 servo3
int32 servo4
int32 servo5
int32 servo6
